version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - my-network

  server:
    container_name: server
    build: ./server
    volumes:
      - .:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
    depends_on:
      - mongo
    networks:
      - my-network

  client:
    container_name: client
    build: ./client
    volumes:
      - .:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - my-network

volumes:
  mongodb:
  node_modules:

networks:
  my-network:
    driver: bridge
